/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.lambda.unit1;

public class Greeter {
    public void greet() {
        System.out.println("Hello World!");
    }

    public void greet(Greeting greeting) {
        greeting.perform();
    }

    public static void main(String[] args) {
        Greeter greeter = new Greeter();
        greeter.greet();

        HelloWorldGreeting helloWorldGreeting = new HelloWorldGreeting();
        greeter.greet(helloWorldGreeting);

        MyLambda myLambdaFunction = () -> System.out.println("Hello world!");
        myLambdaFunction.foo();

        MyAdd addFunction = (int a, int b) -> a + b;

        Greeting lambdaGreeting = () -> System.out.println("Hello world!");
        lambdaGreeting.perform();

        Greeting innerClassGreeting = new Greeting() {
            public void perform() {
                System.out.println("Hello world!");
            }
        };

        greeter.greet(innerClassGreeting);
        greeter.greet(() -> System.out.println("Hello world!"));
    }
}

interface MyLambda {
    void foo();
}

interface MyAdd {
    int add(int x, int y);
}