/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.lambda;

import org.junit.jupiter.api.Test;

import io.lambda.unit1.Greeter;

import static org.junit.jupiter.api.Assertions.*;

class GreeterTest {
    @Test void appHasAGreeting() {
        Greeter classUnderTest = new Greeter();
    }
}
